#!/bin/sh
if [ -d /sys/block/*/$MDEV ] || [ -d /sys/block/$MDEV -a ! -d /sys/block/$MDEV/$MDEV* ]
then
	mkdir -p /mnt/usb/$MDEV
	/etc/mdev/do_mount /dev/$MDEV /mnt/usb/$MDEV -o defaults,noatime,async,errors=continue
fi
