/*
 * Generated by gdbus-codegen 2.40.2. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifndef __LIBGDBUSMEDIAVIDEO_H__
#define __LIBGDBUSMEDIAVIDEO_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for com.aw.Gdbus.mediavideo */

#define TYPE_COM_AW_GDBUS_MEDIAVIDEO (com_aw_gdbus_mediavideo_get_type ())
#define COM_AW_GDBUS_MEDIAVIDEO(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_COM_AW_GDBUS_MEDIAVIDEO, ComAwGdbusMediavideo))
#define IS_COM_AW_GDBUS_MEDIAVIDEO(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_COM_AW_GDBUS_MEDIAVIDEO))
#define COM_AW_GDBUS_MEDIAVIDEO_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_COM_AW_GDBUS_MEDIAVIDEO, ComAwGdbusMediavideoIface))

struct _ComAwGdbusMediavideo;
typedef struct _ComAwGdbusMediavideo ComAwGdbusMediavideo;
typedef struct _ComAwGdbusMediavideoIface ComAwGdbusMediavideoIface;

struct _ComAwGdbusMediavideoIface
{
  GTypeInterface parent_iface;


  gboolean (*handle_method_cmd_get) (
    ComAwGdbusMediavideo *object,
    GDBusMethodInvocation *invocation,
    GVariant *arg_InArg);

  gboolean (*handle_method_cmd_set) (
    ComAwGdbusMediavideo *object,
    GDBusMethodInvocation *invocation,
    GVariant *arg_InArg);

  void (*signalmediovideo) (
    ComAwGdbusMediavideo *object,
    GVariant *arg_Value);

};

GType com_aw_gdbus_mediavideo_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *com_aw_gdbus_mediavideo_interface_info (void);
guint com_aw_gdbus_mediavideo_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void com_aw_gdbus_mediavideo_complete_method_cmd_set (
    ComAwGdbusMediavideo *object,
    GDBusMethodInvocation *invocation,
    GVariant *OutArg);

void com_aw_gdbus_mediavideo_complete_method_cmd_get (
    ComAwGdbusMediavideo *object,
    GDBusMethodInvocation *invocation,
    gint OutArg);



/* D-Bus signal emissions functions: */
void com_aw_gdbus_mediavideo_emit_signalmediovideo (
    ComAwGdbusMediavideo *object,
    GVariant *arg_Value);



/* D-Bus method calls: */
void com_aw_gdbus_mediavideo_call_method_cmd_set (
    ComAwGdbusMediavideo *proxy,
    GVariant *arg_InArg,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_aw_gdbus_mediavideo_call_method_cmd_set_finish (
    ComAwGdbusMediavideo *proxy,
    GVariant **out_OutArg,
    GAsyncResult *res,
    GError **error);

gboolean com_aw_gdbus_mediavideo_call_method_cmd_set_sync (
    ComAwGdbusMediavideo *proxy,
    GVariant *arg_InArg,
    GVariant **out_OutArg,
    GCancellable *cancellable,
    GError **error);

void com_aw_gdbus_mediavideo_call_method_cmd_get (
    ComAwGdbusMediavideo *proxy,
    GVariant *arg_InArg,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_aw_gdbus_mediavideo_call_method_cmd_get_finish (
    ComAwGdbusMediavideo *proxy,
    gint *out_OutArg,
    GAsyncResult *res,
    GError **error);

gboolean com_aw_gdbus_mediavideo_call_method_cmd_get_sync (
    ComAwGdbusMediavideo *proxy,
    GVariant *arg_InArg,
    gint *out_OutArg,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define TYPE_COM_AW_GDBUS_MEDIAVIDEO_PROXY (com_aw_gdbus_mediavideo_proxy_get_type ())
#define COM_AW_GDBUS_MEDIAVIDEO_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_COM_AW_GDBUS_MEDIAVIDEO_PROXY, ComAwGdbusMediavideoProxy))
#define COM_AW_GDBUS_MEDIAVIDEO_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_COM_AW_GDBUS_MEDIAVIDEO_PROXY, ComAwGdbusMediavideoProxyClass))
#define COM_AW_GDBUS_MEDIAVIDEO_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_COM_AW_GDBUS_MEDIAVIDEO_PROXY, ComAwGdbusMediavideoProxyClass))
#define IS_COM_AW_GDBUS_MEDIAVIDEO_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_COM_AW_GDBUS_MEDIAVIDEO_PROXY))
#define IS_COM_AW_GDBUS_MEDIAVIDEO_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_COM_AW_GDBUS_MEDIAVIDEO_PROXY))

typedef struct _ComAwGdbusMediavideoProxy ComAwGdbusMediavideoProxy;
typedef struct _ComAwGdbusMediavideoProxyClass ComAwGdbusMediavideoProxyClass;
typedef struct _ComAwGdbusMediavideoProxyPrivate ComAwGdbusMediavideoProxyPrivate;

struct _ComAwGdbusMediavideoProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  ComAwGdbusMediavideoProxyPrivate *priv;
};

struct _ComAwGdbusMediavideoProxyClass
{
  GDBusProxyClass parent_class;
};

GType com_aw_gdbus_mediavideo_proxy_get_type (void) G_GNUC_CONST;

void com_aw_gdbus_mediavideo_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
ComAwGdbusMediavideo *com_aw_gdbus_mediavideo_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
ComAwGdbusMediavideo *com_aw_gdbus_mediavideo_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void com_aw_gdbus_mediavideo_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
ComAwGdbusMediavideo *com_aw_gdbus_mediavideo_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
ComAwGdbusMediavideo *com_aw_gdbus_mediavideo_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define TYPE_COM_AW_GDBUS_MEDIAVIDEO_SKELETON (com_aw_gdbus_mediavideo_skeleton_get_type ())
#define COM_AW_GDBUS_MEDIAVIDEO_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_COM_AW_GDBUS_MEDIAVIDEO_SKELETON, ComAwGdbusMediavideoSkeleton))
#define COM_AW_GDBUS_MEDIAVIDEO_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_COM_AW_GDBUS_MEDIAVIDEO_SKELETON, ComAwGdbusMediavideoSkeletonClass))
#define COM_AW_GDBUS_MEDIAVIDEO_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_COM_AW_GDBUS_MEDIAVIDEO_SKELETON, ComAwGdbusMediavideoSkeletonClass))
#define IS_COM_AW_GDBUS_MEDIAVIDEO_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_COM_AW_GDBUS_MEDIAVIDEO_SKELETON))
#define IS_COM_AW_GDBUS_MEDIAVIDEO_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_COM_AW_GDBUS_MEDIAVIDEO_SKELETON))

typedef struct _ComAwGdbusMediavideoSkeleton ComAwGdbusMediavideoSkeleton;
typedef struct _ComAwGdbusMediavideoSkeletonClass ComAwGdbusMediavideoSkeletonClass;
typedef struct _ComAwGdbusMediavideoSkeletonPrivate ComAwGdbusMediavideoSkeletonPrivate;

struct _ComAwGdbusMediavideoSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  ComAwGdbusMediavideoSkeletonPrivate *priv;
};

struct _ComAwGdbusMediavideoSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType com_aw_gdbus_mediavideo_skeleton_get_type (void) G_GNUC_CONST;

ComAwGdbusMediavideo *com_aw_gdbus_mediavideo_skeleton_new (void);


G_END_DECLS

#endif /* __LIBGDBUSMEDIAVIDEO_H__ */
