PRODUCT_PACKAGES += \
	libawavs \
	libawh264 \
	libawh265 \
	libawh265soft \
	libawmjpeg \
	libawmjpegplus \
	libawmpeg2 \
	libawmpeg4base \
	libawmpeg4dx \
	libawmpeg4h263 \
	libawmpeg4normal \
	libawmpeg4vp6 \
	libawvp6soft \
	libawvp8 \
	libawvp9soft \
        libawvp9Hw    \
        libawvp9HwAL  \
        libawavs2     \
	libawwmv12soft \
	libawwmv3 \
	libMemAdapter \
	libnormal_audio \
	libsdecoder \
	libvdecoder \
	libvideoengine \
	libVE \
	libvencoder \
    libvenc_base \
    libvenc_common \
	libvenc_h264 \
	libvenc_h265 \
	libvenc_jpeg \
	libOmxCore \
	libOmxVdec \
	libOmxVenc \
	libstagefrighthw \
	cedarc.conf \	

PRODUCT_PACKAGES += \
        libawavs.vendor \
        libawh264.vendor \
        libawh265.vendor \
        libawh265soft.vendor \
        libawmjpeg.vendor \
        libawmjpegplus.vendor \
        libawmpeg2.vendor \
        libawmpeg4base.vendor \
        libawmpeg4dx.vendor \
        libawmpeg4h263.vendor \
        libawmpeg4normal.vendor \
        libawmpeg4vp6.vendor \
        libawvp6soft.vendor \
        libawvp8.vendor \
        libawvp9soft.vendor \
        libawvp9Hw.vendor    \
        libawvp9HwAL.vendor  \
        libawavs2.vendor     \
        libawwmv12soft.vendor \
        libawwmv3.vendor \
        libvideoengine.vendor \
        libVE.vendor \
        libvencoder.vendor \
	libvenc_base.vendor \
	libvenc_common.vendor \
	libvenc_h264.vendor \
	libvenc_h265.vendor \
	libvenc_jpeg.vendor \
        libcdc_base.vendor \
        libMemAdapter.vendor \
        libvdecoder.vendor \
